apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-recognition-admin-api-deployment
  namespace: recognition-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recognition-admin-api-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50