kind: Service
apiVersion: v1
metadata:
  name: recognition-admin-api-service
  namespace: recognition-dev
  annotations:
    # cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
    # cloud.google.com/backend-config: '{"ports": {"80":"recognition-business-backendconfig"}}'
    cloud.google.com/backend-config: '{"default": "recognition-system-backendconfig"}'
    
spec:
  type: NodePort
  selector:
    app: recognition-admin-api
    environment: dev
  ports:
  - port: 80
    targetPort: 8080
  